name: hem_routine_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.18.0
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.2
  firebase_auth: ^3.3.20
  get: ^4.6.5
  flutter_screenutil: ^5.5.3+2

  animated_splash_screen: ^1.2.0
  scroll_date_picker: ^3.4.0
  google_sign_in: ^5.3.3
  flutterfire_ui: ^0.4.2
  onboarding: ^3.1.0
  syncfusion_flutter_gauges: ^20.2.36

  flutter_switch: ^0.3.2
  modal_bottom_sheet: ^2.1.0
  flutter_picker: ^2.0.4
  simple_gesture_detector: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0

fonts:
  - family: GmarketSans
    fonts:
      - asset: fonts/GmarketSansTTFMedium.ttf
  - family: AppleSDGothicNeo
    fonts:
      - asset: fonts/AppleSDGothicNeoM.ttf
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/marker/
    - assets/button/color
    - assets/button/type
    - assets/button/hardness
